//! App self-update via `tauri-plugin-updater`.
//!
//! Two entry points:
//! 1. Startup auto-check (release builds only): `check` -> auto download
//!    (progress logged, no frontend UI) -> system-level confirmation dialog
//!    (`tauri-plugin-dialog`) -> `install` + relaunch.
//! 2. Frontend-driven flow (admin Status page): `check_update_info` feeds a
//!    custom update modal; `download_install_update` streams download progress
//!    back to the frontend, then installs and relaunches.
//!
//! The update payload is a GitHub Releases static JSON (`latest.json`),
//! generated by `tauri-action` in CI.
//!
//! D3: 本模块仅在非 Linux 平台编译（Linux AUR 场景关闭内置 updater，
//! 更新由 pacman 管理），模块声明在 lib.rs 中已条件编译。

use tauri::AppHandle;
use tauri_plugin_dialog::{DialogExt, MessageDialogButtons};
use tauri_plugin_updater::{Update, UpdaterExt};

/// Resolve the pending update, if any. Shared by the auto-check and the
/// frontend-driven flows so the check logic lives in one place.
async fn resolve_update(app: &AppHandle) -> Result<Option<Update>, String> {
    let updater = app
        .updater()
        .map_err(|e| format!("[updater] init failed: {e}"))?;
    updater
        .check()
        .await
        .map_err(|e| format!("[updater] check failed: {e}"))
}

// ─── Startup auto-check (existing behavior, unchanged) ─────────────────────

/// Spawn the startup update check as a detached async task.
pub fn spawn_update_check(app: AppHandle) {
    tauri::async_runtime::spawn(async move {
        run_update_check(app).await;
    });
}

async fn run_update_check(app: AppHandle) {
    let update = match resolve_update(&app).await {
        Ok(Some(u)) => u,
        Ok(None) => {
            log::info!("[updater] no update available");
            return;
        }
        Err(e) => {
            log::error!("{e}");
            return;
        }
    };

    let current = app.package_info().version.to_string();
    log::info!(
        "[updater] update available: {current} -> {}",
        update.version
    );

    // Auto-download the update; progress is reported through the log only.
    let mut downloaded: u64 = 0;
    let bytes = match update
        .download(
            |chunk, total| {
                downloaded += chunk as u64;
                match total {
                    Some(total) if total > 0 => log::info!(
                        "[updater] downloading: {:.1}%",
                        downloaded as f64 / total as f64 * 100.0
                    ),
                    _ => log::info!("[updater] downloaded {downloaded} bytes"),
                }
            },
            || log::info!("[updater] download finished"),
        )
        .await
    {
        Ok(bytes) => bytes,
        Err(e) => {
            log::error!("[updater] download failed: {e}");
            return;
        }
    };

    // System-level confirmation dialog; the callback runs on the main thread.
    // Bytes and the update handle are moved into it, then install runs on a
    // fresh async task so the dialog callback returns immediately.
    let app = app.clone();
    let update = update.clone();
    app.dialog()
        .message(format!(
            "A new version ({}) is ready. Install it and restart piter now?",
            update.version
        ))
        .kind(tauri_plugin_dialog::MessageDialogKind::Info)
        .title("piter update available")
        .buttons(MessageDialogButtons::OkCancelCustom(
            "Install".into(),
            "Later".into(),
        ))
        .show(move |confirmed| {
            if !confirmed {
                log::info!("[updater] user declined, keeping current version");
                return;
            }
            tauri::async_runtime::spawn(async move {
                if let Err(e) = update.install(&bytes) {
                    log::error!("[updater] install failed: {e}");
                    return;
                }
                log::info!(
                    "[updater] installed v{}, relaunching",
                    update.version
                );
                app.restart();
            });
        });
}

// ─── Frontend-driven flow (admin Status page) ───────────────────────────────

/// Check for an available update without downloading.
///
/// Returns `(latest_version, release_notes)` when an update exists, or `None`
/// when the app is already up to date. Errors (network, init) are returned as
/// `Err` so the frontend can show a friendly message.
pub async fn check_update_info(
    app: &AppHandle,
) -> Result<Option<(String, Option<String>)>, String> {
    let update = resolve_update(app).await?;
    match update {
        Some(u) => Ok(Some((u.version.to_string(), u.body))),
        None => Ok(None),
    }
}

/// Download the pending update (streaming progress as `(downloaded, total)`
/// bytes through `on_progress`), install it, and relaunch the app.
pub async fn download_install_update(
    app: AppHandle,
    on_progress: impl Fn(u64, Option<u64>) + Send + 'static,
) -> Result<(), String> {
    let update = resolve_update(&app)
        .await?
        .ok_or_else(|| "no update available".to_string())?;

    let bytes = update
        .download(
            |chunk, total| on_progress(chunk as u64, total),
            || {},
        )
        .await
        .map_err(|e| format!("[updater] download failed: {e}"))?;

    update
        .install(&bytes)
        .map_err(|e| format!("[updater] install failed: {e}"))?;
    log::info!("[updater] installed v{}, relaunching", update.version);
    // `restart` never returns — its `!` type coerces to the function result.
    app.restart()
}
