//! App self-update via `tauri-plugin-updater`.
//!
//! Release builds check for updates on startup (detached async task):
//! `check` -> auto download (progress logged, no frontend UI) -> system-level
//! confirmation dialog (`tauri-plugin-dialog`) -> `install` + relaunch.
//! The update payload is a GitHub Releases static JSON (`latest.json`),
//! generated by `tauri-action` in CI.
//!
//! D3: 本模块仅在非 Linux 平台编译（Linux AUR 场景关闭内置 updater，
//! 更新由 pacman 管理），模块声明在 lib.rs 中已条件编译。

use tauri::AppHandle;
use tauri_plugin_dialog::{DialogExt, MessageDialogButtons};
use tauri_plugin_updater::UpdaterExt;

/// Spawn the startup update check as a detached async task.
pub fn spawn_update_check(app: AppHandle) {
    tauri::async_runtime::spawn(async move {
        run_update_check(app).await;
    });
}

async fn run_update_check(app: AppHandle) {
    let updater = match app.updater() {
        Ok(u) => u,
        Err(e) => {
            log::error!("[updater] init failed: {e}");
            return;
        }
    };

    let update = match updater.check().await {
        Ok(Some(u)) => u,
        Ok(None) => {
            log::info!("[updater] no update available");
            return;
        }
        Err(e) => {
            log::error!("[updater] check failed: {e}");
            return;
        }
    };

    let current = app.package_info().version.to_string();
    log::info!(
        "[updater] update available: {current} -> {}",
        update.version
    );

    // Auto-download the update; progress is reported through the log only.
    let mut downloaded: u64 = 0;
    let bytes = match update
        .download(
            |chunk, total| {
                downloaded += chunk as u64;
                match total {
                    Some(total) if total > 0 => log::info!(
                        "[updater] downloading: {:.1}%",
                        downloaded as f64 / total as f64 * 100.0
                    ),
                    _ => log::info!("[updater] downloaded {downloaded} bytes"),
                }
            },
            || log::info!("[updater] download finished"),
        )
        .await
    {
        Ok(bytes) => bytes,
        Err(e) => {
            log::error!("[updater] download failed: {e}");
            return;
        }
    };

    // System-level confirmation dialog; the callback runs on the main thread.
    // Bytes and the update handle are moved into it, then install runs on a
    // fresh async task so the dialog callback returns immediately.
    let app = app.clone();
    let update = update.clone();
    app.dialog()
        .message(format!(
            "A new version ({}) is ready. Install it and restart piter now?",
            update.version
        ))
        .kind(tauri_plugin_dialog::MessageDialogKind::Info)
        .title("piter update available")
        .buttons(MessageDialogButtons::OkCancelCustom(
            "Install".into(),
            "Later".into(),
        ))
        .show(move |confirmed| {
            if !confirmed {
                log::info!("[updater] user declined, keeping current version");
                return;
            }
            tauri::async_runtime::spawn(async move {
                if let Err(e) = update.install(&bytes) {
                    log::error!("[updater] install failed: {e}");
                    return;
                }
                log::info!(
                    "[updater] installed v{}, relaunching",
                    update.version
                );
                app.restart();
            });
        });
}
